# Generated by Django 2.2 on 2022-08-31 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('email', models.TextField(max_length=30, verbose_name='Электронная почта')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('date_in', models.DateField(auto_now_add=True)),
                ('date_out', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements_app.Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements_app.Category')),
            ],
        ),
    ]
