# Generated by Django 2.2 on 2022-08-31 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0003_auto_20220831_1752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Types',
        ),
    ]
