# Generated by Django 2.2 on 2022-08-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements_app', '0004_auto_20220831_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='view_count',
            field=models.IntegerField(default=0, null=True, verbose_name='Просмотров'),
        ),
    ]
