# Generated by Django 2.2 on 2022-09-18 09:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='users',
            field=models.ForeignKey(default=None, on_delete=django.contrib.auth.models.AnonymousUser, to=settings.AUTH_USER_MODEL),
        ),
    ]
