# Generated by Django 2.2 on 2022-09-18 13:02

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_auto_20220918_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='users',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.contrib.auth.models.AnonymousUser, to=settings.AUTH_USER_MODEL),
        ),
    ]
