# Generated by Django 2.2 on 2022-09-18 13:07

import datetime
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_auto_20220918_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='anon_user',
            field=models.CharField(max_length=50, verbose_name='Имя анонима'),
            preserve_default=False,
        ),
    ]
