# Generated by Django 2.2 on 2022-09-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0004_comment_anon_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='anon_user',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя анонима'),
        ),
    ]
