# Generated by Django 2.2 on 2022-09-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ferifikate',
            field=models.BooleanField(blank=True, null=True, verbose_name='Верефикация'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
