# Generated by Django 2.2 on 2022-09-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0007_auto_20220919_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'permissions': (('can_publish', 'Может публиковать'),), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новость'},
        ),
    ]
