# Generated by Django 2.2 on 2022-09-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0008_auto_20220923_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('vereficate', 'Верефикация пользователя'),), 'verbose_name': 'Верефикация', 'verbose_name_plural': 'Верефикация'},
        ),
    ]
