# Generated by Django 2.2 on 2022-09-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0009_auto_20220923_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='moderate',
            field=models.BooleanField(default=False),
        ),
    ]
