# Generated by Django 2.2 on 2022-09-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0010_news_moderate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='moderate',
            field=models.BooleanField(default=False, verbose_name='Модерация'),
        ),
    ]
