# Generated by Django 2.2 on 2022-09-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0011_auto_20220923_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тэг'),
        ),
    ]
